### ISSUE TITLE
Not building in web

### ISSUE THREAD

**Issue by emuguy1** [astudilloalex/flutter_gradient_text#1]
As soon as I add the package and Element for web comes an unimplemented Error although gradient_text should be Web compatible.
On phone working fine

**Comment by astudilloalex** [comment]
> As soon as I add the package and Element for web comes an unimplemented Error although gradient_text should be Web compatible. On phone working fine

Hello, thanks for post your issue, please add a minimum reproducible code, because, I just tested and it works fine.
Check text on: https://enlargeable-scratch.000webhostapp.com/#/

**Comment by emuguy1** [comment]
`import 'package:flutter/material.dart';


void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SHARING - einfach Dinge teilen',
      theme: ThemeData(
        primaryColor: Colors.white,
      ),
      home: MyHomePage(title: 'SHARING.'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title,
          style: TextStyle(fontSize: 20.0, fontWeight: FontWeight.bold),),
        actions: [
          TextButton(
              style: TextButton.styleFrom(
                primary: Color.fromRGBO(21, 128, 61, 1),
              ),
              onPressed: () {
                ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('This is a snackbar')));
              },
              child: Text("Einloggen")),
          TextButton(
            child: Text("Registrieren"),
            style: TextButton.styleFrom(
              padding: const EdgeInsets.all(16.0),
              primary: Color.fromRGBO(220, 252, 231, 1),
              backgroundColor: Color.fromRGBO(21, 128, 61, 1),
            ),
            onPressed: () {
              print('Pressed');
            },
          )
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Teilen macht',
              style: TextStyle(fontSize: 40.0, fontWeight: FontWeight.bold),
            ),
            Text('glücklich.'),

            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`
With this code everything works fine. This is just a quick and dirty example application.
Then I run the needed command:
`flutter pub add simple_gradient_text`

Add the import at the top of my main App and added:
`GradientText(
              'glücklich.',
              style: TextStyle(
                fontSize: 40.0,
              ),
              gradientType: GradientType.radial,
              radius: 2.5,
              colors: [
                Color.fromRGBO(29, 78, 216, 1),
                Color.fromRGBO(126, 34, 206, 1),
                Color.fromRGBO(190, 24, 93, 1),
              ],
            ),
`
This works fine in application but fails in Chrome or Edge.
Same problem when I do it with the example you provide on your website:
`GradientText(
                'Gradient Text Example',
                style: TextStyle(
                  fontSize: 40.0,
                ),
                colors: [
                  Colors.blue,
                  Colors.red,
                  Colors.teal,
                ],
              ),
`
The error I got was:

![Screenshot 2022-04-21 175041](https://user-images.githubusercontent.com/29579705/164699123-6f36d03d-55ce-46d8-a2c1-708d487de421.png)

I excuse me if this is an error on my side, as this is kind of my first steps towards flutter but couldn't find any other problem and as soon as I remove the package and the Lines with the example, everything works fine.

**Comment by astudilloalex** [comment]
The package use ShaderMask to create gradients. Flutter (>=2.5.0) required.
Check the version of Flutter you're using, as ShaderMask previously didn't support the web.
Run `flutter upgrade`.

Hello, the problem is not with the package, check if it appears inside the pubspec.yaml file correctly imported.
![image](https://user-images.githubusercontent.com/48831301/164802849-7ca98efb-13d8-4c63-8b86-2ee9973f949a.png)
If you have other packages imported try removing and testing without using any other packages.

I used your code and tried to reproduce the error, but it works fine.

```
import 'package:flutter/material.dart';
import 'package:simple_gradient_text/simple_gradient_text.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SHARING - einfach Dinge teilen',
      theme: ThemeData(
        primaryColor: Colors.white,
      ),
      home: const MyHomePage(title: 'SHARING.'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.title,
          style: const TextStyle(fontSize: 20.0, fontWeight: FontWeight.bold),
        ),
        actions: [
          TextButton(
              style: TextButton.styleFrom(
                primary: const Color.fromRGBO(21, 128, 61, 1),
              ),
              onPressed: () {
                ScaffoldMessenger.of(context).showSnackBar(
                    const SnackBar(content: Text('This is a snackbar')));
              },
              child: const Text("Einloggen")),
          TextButton(
            child: const Text("Registrieren"),
            style: TextButton.styleFrom(
              padding: const EdgeInsets.all(16.0),
              primary: const Color.fromRGBO(220, 252, 231, 1),
              backgroundColor: const Color.fromRGBO(21, 128, 61, 1),
            ),
            onPressed: () {
              print('Pressed');
            },
          )
        ],
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'Teilen macht',
              style: TextStyle(fontSize: 40.0, fontWeight: FontWeight.bold),
            ),
            const Text('glücklich.'),
            const Text(
              'You have pushed the button this many times:',
            ),
            GradientText(
              'glücklich.',
              style: const TextStyle(
                fontSize: 40.0,
              ),
              gradientType: GradientType.radial,
              radius: 2.5,
              colors: const [
                Color.fromRGBO(29, 78, 216, 1),
                Color.fromRGBO(126, 34, 206, 1),
                Color.fromRGBO(190, 24, 93, 1),
              ],
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

![image](https://user-images.githubusercontent.com/48831301/164803157-b45692bd-8c81-4d75-816a-33f90d13afb4.png)

**Comment by astudilloalex** [comment]
The error is not caused by the package.

**Comment by emuguy1** [comment]
Thanks, found the issue unfortunately my flutter version still was 2.0.6. Upgraded to 2.10.5 and everything works now. Thanks for the help.
Maybe you could add this to the package information. Thanks for you're help
