### ISSUE TITLE
Flutter Web Crash on Safari

### ISSUE THREAD

**Issue by 10knThanh** [astudilloalex/flutter_gradient_text#5]
I have an issue with Flutter Web on Safari. My website crashes as soon as Gradient Text is displayed. Does anyone have a way to fix it?

**Comment by astudilloalex** [comment]
Hello, thanks for your reports but I need more information, like example code and error throwed, and dependencies you use on your application, because the package works correctly.
- But the version of dart in `pub.dev` was updated.

**Comment by astudilloalex** [comment]
Because I can not reproduce exception and feedback not provided; I proceed to close
